id: IF510AF24
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:57:59+00:00'
last_modified: '2022-06-16T05:00:56.096405+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19296
  title: ཡང་གསང་རྟ་ཕག་གི་བསྙེན་ཡིག་མཁས་གྲུབ་དུ་མའི་དགོངས་གསལ་ཉི་མའི་འོད་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    75C9:
      image_group_id: I8LS19298
      title: Volume 1 of yang gsang rta phag gi bsnyen yig mkhas grub du ma'i dgongs
        gsal nyi ma'i 'od zer/
      total_pages: 424
      order: 1
      base_file: 75C9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
